# Generated by Django 4.0.6 on 2023-04-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tissue', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('j_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=255)),
                ('second', models.CharField(blank=True, max_length=255, null=True)),
                ('first_duration', models.DateTimeField(blank=True, null=True)),
                ('second_duration', models.DateTimeField(blank=True, null=True)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.project'),
        ),
    ]
