# Generated by Django 4.0.6 on 2023-04-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_image_i_id_alter_judgement_j_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend_api.project'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgement', to='backend_api.image'),
        ),
    ]
