# Generated by Django 4.1 on 2023-04-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0003_alter_image_p_id_alter_judgement_i_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("u_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("mail", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="u_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend_api.user",
            ),
            preserve_default=False,
        ),
    ]
