# Generated by Django 4.1 on 2023-05-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0004_user_project_u_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="resolution",),
        migrations.RemoveField(model_name="image", name="tissue",),
        migrations.RemoveField(model_name="project", name="path",),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="path",
            field=models.CharField(default="/", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="u_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="backend_api.user",
            ),
        ),
    ]
