# Generated by Django 3.2.19 on 2023-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_remove_image_resolution_remove_image_tissue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='judgement',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
