# Generated by Django 3.2.19 on 2023-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20230526_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='first_duration',
            new_name='firstDuration',
        ),
        migrations.RenameField(
            model_name='judgement',
            old_name='first',
            new_name='firstJudge',
        ),
        migrations.RenameField(
            model_name='judgement',
            old_name='second_duration',
            new_name='secondDuration',
        ),
        migrations.RenameField(
            model_name='judgement',
            old_name='second',
            new_name='secondJudge',
        ),
    ]
