# Generated by Django 3.2.19 on 2023-05-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_auto_20230526_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='backend_api.image'),
        ),
    ]
